[package]
name = "surfpvparena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
dotenv = "0.15"
glob = "0.3"
once_cell = "1.9"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
songbird = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.serenity]
version = "0.10"
features = ["cache", "framework", "standard_framework", "voice"]

[dependencies.tokio]
version = "1.15"
features = ["macros", "rt-multi-thread", "signal"]