[package]
name = "surfpvparena"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
glob = "0.3"
moka = { version = "0.6", features = ["future"] }
mp3-metadata = "0.3"
once_cell = "1.9"
puremp3 = "0.1"
regex = "1.5"
serenity = { version = "0.10", features = ["cache", "framework", "standard_framework", "voice"] }
songbird = "0.2"
strsim = "0.10"
tokio = { version = "1.15", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
