[package]
name = "ssspambot"
version = "0.1.0"
edition = "2021"
default-run = "ssspambot"

[dependencies]
anyhow = "1.0.55"
async_zip = "0.0.6"
bincode = "1.3.3"
chrono = "0.4.19"
cloud-storage = "0.11.0"
counter = "0.5.3"
derive_builder = "0.10.2"
dotenv = "0.15.0"
glob = "0.3.0"
humantime = "2.1.0"
maud = "0.23.0"
moka = { version = "0.7.2", features = ["future"] }
mp3-metadata = "0.3.3"
mp4ameta = "0.11.0"
nom = "7.1.0"
once_cell = "1.9.0"
prettytable-rs = "0.8.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serenity = { version = "0.10.10", features = ["cache", "framework", "standard_framework", "voice"] }
songbird = "0.2.2"
strsim = "0.10.0"
structopt = "0.3.26"
systemstat = "0.1.10"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.31"
tracing-futures = "0.2.5"
tracing-subscriber = "0.3.9"
