[package]
name = "ssspambot"
version = "0.1.0"
edition = "2021"
default-run = "ssspambot"

[dependencies]
bincode = "1.3.3"
counter = "0.5.2"
dotenv = "0.15.0"
futures = "0.3.19"
glob = "0.3.0"
moka = { version = "0.6.2", features = ["future"] }
mp3-metadata = "0.3.3"
once_cell = "1.9.0"
pest = "2.1.3"
pest_derive = "2.1.0"
prettytable-rs = "0.8.0"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serenity = { version = "0.10.9", features = ["cache", "framework", "standard_framework", "voice"] }
songbird = "0.2.0"
strsim = "0.10.0"
structopt = "0.3.25"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
tracing-futures = "0.2.5"
