[package]
name = "surfpvparena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
songbird = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

[dependencies.serenity]
version = "0.10"
features = ["client", "standard_framework", "voice"]

[dependencies.tokio]
version = "1.15"
features = ["macros", "rt-multi-thread", "signal"]