[tasks.upload-sounds]
script_runner = "python"
script_extension = "py"
script = '''
import datetime
import os
import shutil
import subprocess

today = datetime.date.today().isoformat()
dest = today + '.zip'
shutil.make_archive(today, 'zip', root_dir='dist/sound')

print(dest)
subprocess.run(['ls'])
subprocess.run(['gsutil', 'cp', dest, f'gs://surfpvparena/{dest}'])

os.remove(dest)
'''

[tasks.convert-mp3-to-m4a]
script_runner = "python"
script_extension = "py"
script = '''
import pathlib
import subprocess

for infile in pathlib.Path('dist/sound').glob('*.mp3'):
    outfile = pathlib.Path(f'dist/m4a/{infile.stem}.m4a')
    if not outfile.exists():
        cmd = ['ffmpeg', '-i', str(infile), str(outfile)]
        subprocess.run(cmd, capture_output=True)
'''

[tasks.update-server]
script_runner = "@shell"
script = '''
gcloud beta compute instance-groups managed rolling-action replace instance-group-1 --max-surge=1 --max-unavailable=0 --min-ready=30s --replacement-method=substitute --zone=asia-northeast1-b
'''
