name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D clippy::all -W clippy::nursery
      - run: cargo fmt -- --check
      - uses: hadolint/hadolint-action@v1.6.0
        name: Lint Dockerfile
        with:
          ignore: DL3059
